<?php
/**
 WeArePlanet Magento 2
 *
 * This Magento 2 extension enables to process payments with WeArePlanet (https://www.weareplanet.com).
 *
 * @package WeArePlanet_Payment
 * @author Planet Merchant Services Ltd (https://www.weareplanet.com)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */

/** @var $block \WeArePlanet\Payment\Block\DeviceSession */
?>
<script type="text/x-magento-init">
{
    "*": {
        "WeArePlanet_Payment/js/weareplanet-device": {
            "scriptUrl" : "<?=$block->escapeHtml($block->getScriptUrl())?>",
            "identifierUrl" : "<?=$block->escapeHtml($block->getSessionIdentifierUrl())?>"
        }
    }
}
</script>