<?php
/**
 * WeArePlanet Magento 2
 *
 * This Magento 2 extension enables to process payments with WeArePlanet (https://www.weareplanet.com).
 *
 * @package WeArePlanet_Payment
 * @author Planet Merchant Services Ltd (https://www.weareplanet.com)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */
/**
 * @formatter:off
 */

/** @var $block \WeArePlanet\Payment\Block\Adminhtml\Sales\Order\Invoice\View */
?>

<?php if ($block->isCapturePending()) : ?>
	<div class="messages">
		<div class="message message-warning warning">
			<?=$block->escapeHtml(\__('The capture has been requested but could not be completed yet. The invoice will be updated, as soon as the capture is done.'))?>
		</div>
	</div>
<?php endif; ?>